DEVICEINFO_VERSION = 1.0
DEVICEINFO_SITE = $(BR2_EXTERNAL_WAITAHA_PATH)/package/deviceinfo
DEVICEINFO_SITE_METHOD = local
DEVICEINFO_INSTALL_TARGET = YES

define DEVICEINFO_INSTALL_TARGET_CMDS
	echo -n $(BR2_PACKAGE_DEVICEINFO_INFO) > $(TARGET_DIR)/etc/deviceinfo
endef

$(eval $(generic-package))