#!/bin/sh

umask 077

start() {
	printf "Starting tqftpserv: "
	start-stop-daemon --start --quiet --make-pidfile --pidfile /var/run/tqftpserv.pid --background --exec /usr/bin/tqftpserv
	echo "OK"
}
stop() {
	printf "Stopping tqftpserv: "
	start-stop-daemon --stop --quiet --pidfile /var/run/tqftpserv.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
