#!/bin/sh
umask 077

start() {
	printf "Starting udhcpd: "
	/usr/sbin/udhcpd
	echo "OK"
}
stop() {
	printf "Stopping udhcpd: "
	killall udhcpd
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

