#!/bin/sh

umask 077

start() {
	printf "Starting rmtfs: "
	start-stop-daemon --start --quiet --make-pidfile --pidfile /var/run/rmtfs.pid --background --exec /usr/sbin/rmtfs -- -P -r
	echo "OK"
}
stop() {
	printf "Stopping rmtfs: "
	start-stop-daemon --stop --quiet --pidfile /var/run/rmtfs.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
